[G29 Racing Wheel]

steering_wheel = 0
# throttle = 1  # G29
# brake = 2  # G29
throttle = 3
brake = 4
sensitivity = 0.5
k1 = 2
k2 = 1.6

respawn = 13
hud = 14
camera = 15
weathers = 16

# Right flap
reverse = 4

# Lights
lights = 11

# Left blinker
left_blinker = 7
# Right blinker
right_blinker = 6